### ISSUE TITLE
Javascript

### ISSUE THREAD

**Issue by avamariee** [avamariee/pet-adoption-quiz#4]
## Description

> Button functionality, i.e onclick will open quiz.html from the index.html file.
> Save user location through initial modal popup, asks for name & state?
> Fetch from Petfinder API
> Fetch from Cat API
> Fetch from Dog API
> Loop through questions array, display each question individually and save answers based on boolean responses.
> Display random images from the cat/dog API on either side of the quiz.
> Displays results and return related adoptions from Petfinder API at the end.

**Comment by tessaustin** [comment]
Skeleton outlay of questions with choices. Fully functional. 
edited html just so I could see if my js would execute.

I still need to attach dog/cat to each question choice for final determination of dog or cat person.
